homepage:
  url:    /
  param:  { module: default, action: index, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

##-------------------------- shfSecurity --------------------------##
shfSecurity_index:
  url:    /signin
  param:  { module: shfSecurity, action: index, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

shfSecurity_login:
  url:    /login
  param:  { module: shfSecurity, action: login, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php
    - model/base/usuarioCredencialBaseTableClass.php
    - model/usuarioCredencialTableClass.php
    - model/base/credencialBaseTableClass.php
    - model/credencialTableClass.php
    - model/base/recordarMeBaseTableClass.php
    - model/recordarMeTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php

shfSecurity_logout:
  url:    /logout
  param:  { module: shfSecurity, action: logout, format: html }
  load:
    - model/base/recordarMeBaseTableClass.php
    - model/recordarMeTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php

shfSecurity_noPermission:
  url:    /sin_permisos
  param:  { module: shfSecurity, action: noPermission, format: html }

shfSecurity_exception:
  url:    /exception
  param:  { module: shfSecurity, action: exception, format: html }
##-------------------------- shfSecurity --------------------------##

##-------------------------- EJEMPLO --------------------------##
default_index:
  url:    /usuarios/index
  param:  { module: default, action: index, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_insert:
  url:    /usuarios/insertar
  param:  { module: default, action: insert, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_create:
  url:    /usuarios/crear
  param:  { module: default, action: create, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_edit:
  url:    /usuario/editar
  param:  { module: default, action: edit, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_update:
  url:    /usuario/actualizar
  param:  { module: default, action: update, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_delete:
  url:    /usuario/eliminar
  param:  { module: default, action: delete, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

default_deleteSelect:
  url:    /usuario/eliminarSeleccion
  param:  { module: default, action: deleteSelect, format: html }
  load:
    - model/base/usuarioBaseTableClass.php
    - model/usuarioTableClass.php

#default_reporte:
#  url:    /usuario/reporte
#  param:  { module: default, action: report, format: pdf }
#  load:
#    - libs/fpdf/fpdf.php
##-------------------------- EJEMPLO --------------------------##



##-------------------------- ACUDIENTE --------------------------##

acudiente_index:
  url:    /acudiente/index
  param:  { module: acudiente, action: index, format: html }
  load:
    - model/base/acudienteBaseTableClass.php
    - model/acudienteTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    
acudiente_insert:
  url:    /acudiente/insertar
  param:  { module: acudiente, action: insert, format: html }
  load:
    - model/base/acudienteBaseTableClass.php
    - model/acudienteTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/tipoAcudienteTableClass.php
    - model/base/tipoAcudienteBaseTableClass.php

acudiente_create:
  url:    /acudiente/crear
  param:  { module: acudiente, action: create, format: html }
  load:
    - model/base/acudienteBaseTableClass.php
    - model/acudienteTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/tipoAcudienteBaseTableClass.php
    - model/tipoAcudienteTableClass.php
    
    
##-------------------------- ASIGNATURA --------------------------##

asignatura_index:
  url:    /asignatura/index
  param:  { module: asignatura, action: index, format: html }
  load:
    - model/base/asignaturaBaseTableClass.php
    - model/asignaturaTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/tipoAsignaturaBaseTableClass.php
    - model/tipoAsignaturaTableClass.php
  
    
asignatura_insert:
  url:    /asignatura/insertar
  param:  { module: asignatura, action: insert, format: html }
  load:
    - model/base/asignaturaBaseTableClass.php
    - model/asignaturaTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/tipoAsignaturaBaseTableClass.php
    - model/tipoAsignaturaTableClass.php

asignatura_create:
  url:    /asignatura/crear
  param:  { module: asignatura, action: create, format: html }
  load:
    - model/base/asignaturaBaseTableClass.php
    - model/asignaturaTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/tipoAsignaturaBaseTableClass.php
    - model/tipoAsignaturaTableClass.php
    
asignatura_edit:
  url:    /asignatura/editar
  param:  { module: asignatura, action: edit, format: html }
  load:
    - model/base/asignaturaBaseTableClass.php
    - model/asignaturaTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/tipoAsignaturaBaseTableClass.php
    - model/tipoAsignaturaTableClass.php

asignatura_update:
  url:    /asignatura/actualizar
  param:  { module: asignatura, action: update, format: html }
  load:
    - model/base/asignaturaBaseTableClass.php
    - model/asignaturaTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/tipoAsignaturaBaseTableClass.php
    - model/tipoAsignaturaTableClass.php
    
asignatura_delete:
  url:    /asignatura/eliminar
  param:  { module: asignatura, action: delete, format: json }
  load:
    - model/base/asignaturaBaseTableClass.php
    - model/asignaturaTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/tipoAsignaturaBaseTableClass.php
    - model/tipoAsignaturaTableClass.php

asignatura_deleteSelect:
  url:    /asignatura/eliminarSeleccion
  param:  { module: asignatura, action: deleteSelect, format: html }
  load:
    - model/base/asignaturaBaseTableClass.php
    - model/asignaturaTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/tipoAsignaturaBaseTableClass.php
    - model/tipoAsignaturaTableClass.php
    
    
##-------------------------- BOLETIN --------------------------##

boletin_index:
  url:    /boletin/index
  param:  { module: boletin, action: index, format: html }
  load:
    - model/base/cabeceraBoletinBaseTableClass.php
    - model/cabeceraBoletinTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/estudianteBaseTableClass.php
    - model/estudianteTableClass.php
    - model/base/gradoBaseTableClass.php
    - model/gradoTableClass.php
  
    
boletin_insert:
  url:    /boletin/insertar
  param:  { module: boletin, action: insert, format: html }
  load:
    - model/base/cabeceraBoletinBaseTableClass.php
    - model/cabeceraBoletinTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/estudianteBaseTableClass.php
    - model/estudianteTableClass.php
    - model/base/gradoBaseTableClass.php
    - model/gradoTableClass.php

boletin_create:
  url:    /boletin/crear
  param:  { module: boletin, action: create, format: html }
  load:
    - model/base/cabeceraBoletinBaseTableClass.php
    - model/cabeceraBoletinTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/estudianteBaseTableClass.php
    - model/estudianteTableClass.php
    - model/base/gradoBaseTableClass.php
    - model/gradoTableClass.php
    
boletin_edit:
  url:    /boletin/editar
  param:  { module: boletin, action: edit, format: html }
  load:
    - model/base/cabeceraBoletinBaseTableClass.php
    - model/cabeceraBoletinTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/estudianteBaseTableClass.php
    - model/estudianteTableClass.php
    - model/base/gradoBaseTableClass.php
    - model/gradoTableClass.php

boletin_update:
  url:    /boletin/actualizar
  param:  { module: boletin, action: update, format: html }
  load:
    - model/base/cabeceraBoletinBaseTableClass.php
    - model/cabeceraBoletinTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/estudianteBaseTableClass.php
    - model/estudianteTableClass.php
    - model/base/gradoBaseTableClass.php
    - model/gradoTableClass.php
    
boletin_delete:
  url:    /boletin/eliminar
  param:  { module: boletin, action: delete, format: json }
  load:
    - model/base/cabeceraBoletinBaseTableClass.php
    - model/cabeceraBoletinTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/estudianteBaseTableClass.php
    - model/estudianteTableClass.php
    - model/base/gradoBaseTableClass.php
    - model/gradoTableClass.php

boletin_deleteSelect:
  url:    /boletin/eliminarSeleccion
  param:  { module: boletin, action: deleteSelect, format: html }
  load:
    - model/base/cabeceraBoletinBaseTableClass.php
    - model/cabeceraBoletinTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/estudianteBaseTableClass.php
    - model/estudianteTableClass.php
    - model/base/gradoBaseTableClass.php
    - model/gradoTableClass.php

boletin_ver:
  url:    /boletin/ver
  param:  { module: boletin, action: ver, format: html }
  load:
    - model/base/cabeceraBoletinBaseTableClass.php
    - model/cabeceraBoletinTableClass.php
    - hooks/logHookClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/bitacoraBaseTableClass.php
    - model/bitacoraTableClass.php
    - model/base/estudianteBaseTableClass.php
    - model/estudianteTableClass.php
    - model/base/gradoBaseTableClass.php
    - model/gradoTableClass.php
    - model/base/detalleBoletinBaseTableClass.php
    - model/detalleBoletinTableClass.php